name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: run a one-line script
      run: echo hello, world!

    - name: run a multiple-line script
      run: |
        echo add actions to build
        echo test, and deplo your project
